### ISSUE TITLE
Possible User Enumeration

### ISSUE THREAD

**Issue by LuccaPrado** [Cv-Keep/cvkeep-backend#10]
I've noticed that malicious users can use the username check endpoint to perform an user enumeration. 
This alone isn't a serious problem, but, on getcredentials request we have an email disclosure (I'll try to submit an PR for this today), so an malicious user could pick email of every user and use for spam or things like that.

**Comment by felippe-regazio** [comment]
The /getcredentials must return the email only for your logged user and only when logged, otherwise must not. I'll do some checks and drop a status here. Thanks Lucca ; )

**Comment by netojocelino** [comment]
indeed `/getcredentials` does not returns email, but, when access `/curriculum/get` is possible to get the user private email. I request an [Pull Request](https://github.com/Cv-Keep/cvkeep-backend/pull/16) to mitigate this problem

**Comment by felippe-regazio** [comment]
Thank you @netojocelino, the PR has been merged!
