### ISSUE TITLE
Url de background

### ISSUE THREAD

**Issue by LuccaPrado** [Cv-Keep/cvkeep-backend#6]
Percebi que nas chamadas é possível alterar a url da foto para uma que não esteja na lista, exemplo:

![image](https://user-images.githubusercontent.com/8813731/137815635-dd7a981a-7cc3-42da-9ccf-7c396bd2cf3a.png)

Esse bug parece perfeitamente manipulável para virar uma feature rsrs

**Comment by LuccaPrado** [comment]
Abri como back pois é pela tratativa do back, mas, fiquei em dúvida se deveria ser front

**Comment by felippe-regazio** [comment]
Cara, vc acha que pode ser util transformar esse bug em feature e deixar o usuário setar uma URL custom pra background?
